name: qr_flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  mobile_scanner: ^7.4.0
  path: ^1.9.1
  qr_flutter: ^4.1.0
  sqflite: ^2.4.3
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.6
  url_launcher: ^6.3.2
  wifi_iot: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_logo.png
