name: Build & Release Mobile APKs

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  # === MÁY ẢO 1: BUILD FLUTTER ===
  build-flutter:
    name: Build Flutter APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
        working-directory: ./QR_Project_Workspace/Flutter_App
      - run: flutter build apk --release
        working-directory: ./QR_Project_Workspace/Flutter_App
      
      # Đổi tên file cho chuyên nghiệp
      - run: mv ./QR_Project_Workspace/Flutter_App/build/app/outputs/flutter-apk/app-release.apk ./QR_Manager_Flutter.apk
      
      - uses: actions/upload-artifact@v4
        with:
          name: Flutter_APK
          path: ./QR_Manager_Flutter.apk

  # === MÁY ẢO 2: BUILD ANDROID NATIVE ===
  build-android-native:
    name: Build Android Native APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: chmod +x ./gradlew
        working-directory: ./QR_Project_Workspace/Android_Native 
      - run: ./gradlew assembleDebug -Dorg.gradle.java.home="$JAVA_HOME"
        working-directory: ./QR_Project_Workspace/Android_Native
        
      # Đổi tên file cho chuyên nghiệp
      - run: mv ./QR_Project_Workspace/Android_Native/app/build/outputs/apk/debug/app-debug.apk ./QR_Manager_Android.apk
      
      - uses: actions/upload-artifact@v4
        with:
          name: Android_APK
          path: ./QR_Manager_Android.apk

  # === MÁY ẢO 3: GOM FILE VÀ ĐĂNG LÊN RELEASE ===
  create-release:
    name: Xuất bản lên Release
    needs: [build-flutter, build-android-native] # Yêu cầu chờ 2 máy ảo trên chạy xong
    runs-on: ubuntu-latest
    permissions:
      contents: write # Quyền tạo Release
    steps:
      - name: Tải Flutter APK từ máy ảo 1
        uses: actions/download-artifact@v4
        with:
          name: Flutter_APK
          
      - name: Tải Android APK từ máy ảo 2
        uses: actions/download-artifact@v4
        with:
          name: Android_APK
          
      - name: Đăng tải lên trang Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.apk" # Gom tất cả file có đuôi .apk
          tag: "Latest"
          name: "Bản cài đặt mới nhất 🚀"
          body: "Bấm vào các file **.apk** bên dưới để tải trực tiếp về điện thoại. Bản phát hành này được tự động build và cập nhật từ mã nguồn mới nhất."
          allowUpdates: true # Tự động xóa file cũ, cập nhật file mới
